services:
  - type: web
    name: huquqchi-bot
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: BOT_TOKEN
        sync: false
      - key: MINI_APP_URL
        value: https://huquqchi-lovat.vercel.app


